[algokit]
min_version = "v2.0.0"

[project]
type = "sdk"
name = 'use-wallet'

[project.run]
build = { commands = ['env NODE_OPTIONS=--max-old-space-size=4096 pnpm run build:packages'], description = 'Build use-wallet' }
build2 = { commands = ['env NODE_OPTIONS=--max-old-space-size=4096 pnpm run build:packages'], description = 'Build use-wallet' }
